import json
from datetime import datetime
from pathlib import Path

import pandas as pd
from ollama import chat

from tools.missing_normalization import bad_values
from tools.value_classifier import classify_values
from tools.word_to_num import word_to_num
from tools.numeric_cleaner import numeric_cleaner
from tools.datetime_cleaner import datetime_cleaner
from tools.categorical_cleaner import categorical_cleaner
from tools.dtype_converter import dtype_converter
from tools.missing_value_handler import (
    missing_value_handler,
    AVAILABLE_METHODS,
)


DEFAULT_MODEL = "qwen3:4b"


class DumE:
    """
    Dum-E V0 - deterministic data-cleaning orchestrator.

    Qwen3 is used for semantic column-type inference.
    The actual transformations are performed by deterministic tools.
    User decisions are required for unresolved missing values.
    A Markdown execution report is generated automatically after a
    successful cleaning run.
    """

    ALLOWED_TYPES = {
        "id",
        "numeric",
        "categorical",
        "datetime",
        "text",
    }

    def __init__(
        self,
        model: str = DEFAULT_MODEL,
        report_path: str = "report.md",
    ):
        self.model = model
        self.report_path = report_path
        self.schema = {}
        self.events = []

    # ================================================================
    # REPORT / LOGGING
    # ================================================================

    def log(self, message: str):
        """Print a message to the terminal."""
        print(message)

    def record(self, stage: str, description: str):
        """Record a structured event for report.md."""
        self.events.append(
            {
                "stage": stage,
                "description": description,
            }
        )

    @staticmethod
    def _changed_cells(before: pd.DataFrame, after: pd.DataFrame):
        """
        Return a small list of actual cell-level changes.
        Useful for the audit report without dumping the whole DataFrame.
        """
        changes = []

        common_columns = [
            col for col in before.columns
            if col in after.columns
        ]

        for column in common_columns:
            before_col = before[column]
            after_col = after[column]

            for index in before.index.intersection(after.index):
                old = before_col.loc[index]
                new = after_col.loc[index]

                old_missing = pd.isna(old)
                new_missing = pd.isna(new)

                if old_missing and new_missing:
                    continue

                if old_missing != new_missing or old != new:
                    changes.append(
                        {
                            "column": column,
                            "index": index,
                            "old": old,
                            "new": new,
                        }
                    )

        return changes

    def _record_dataframe_changes(
        self,
        stage: str,
        before: pd.DataFrame,
        after: pd.DataFrame,
    ):
        changes = self._changed_cells(before, after)

        if not changes:
            self.record(stage, "No cell values changed.")
            return

        lines = [
            f"Changed cells: `{len(changes)}`",
            "",
            "| Column | Row | Before | After |",
            "|---|---:|---|---|",
        ]

        # Keep report readable for large datasets.
        display_changes = changes[:50]

        for change in display_changes:
            lines.append(
                f"| `{change['column']}` | `{change['index']}` | "
                f"`{change['old']}` | `{change['new']}` |"
            )

        if len(changes) > 50:
            lines.extend(
                [
                    "",
                    f"> Only the first 50 of {len(changes)} changes are shown.",
                ]
            )

        self.record(stage, "\n".join(lines))

    def write_report(
        self,
        original_df: pd.DataFrame,
        cleaned_df: pd.DataFrame,
        started_at: datetime,
        finished_at: datetime,
    ):
        """Create the Markdown audit report generated by Dum-E itself."""

        report = [
            "# Dum-E V0 Cleaning Report",
            "",
            "## Run Information",
            "",
            f"- **Model:** `{self.model}`",
            f"- **Started:** `{started_at.isoformat(timespec='seconds')}`",
            f"- **Finished:** `{finished_at.isoformat(timespec='seconds')}`",
            f"- **Rows:** `{len(original_df)}` → `{len(cleaned_df)}`",
            f"- **Columns:** `{len(original_df.columns)}` → `{len(cleaned_df.columns)}`",
            "",
            "## Inferred Schema",
            "",
            "| Column | Semantic Type |",
            "|---|---|",
        ]

        for column, dtype in self.schema.items():
            report.append(f"| `{column}` | `{dtype}` |")

        report.extend(
            [
                "",
                "## Changes Made",
                "",
            ]
        )

        for number, event in enumerate(self.events, start=1):
            report.extend(
                [
                    f"### {number}. {event['stage']}",
                    "",
                    event["description"],
                    "",
                ]
            )

        report.extend(
            [
                "## Final Data Types",
                "",
                "| Column | dtype |",
                "|---|---|",
            ]
        )

        for column, dtype in cleaned_df.dtypes.items():
            report.append(f"| `{column}` | `{dtype}` |")

        report.extend(
            [
                "",
                "## Remaining Missing Values",
                "",
                "| Column | Missing Count | Percentage |",
                "|---|---:|---:|",
            ]
        )

        total_rows = len(cleaned_df)

        for column in cleaned_df.columns:
            count = int(cleaned_df[column].isna().sum())
            percentage = (count / total_rows * 100) if total_rows else 0
            report.append(
                f"| `{column}` | `{count}` | `{percentage:.2f}%` |"
            )

        report.extend(
            [
                "",
                "## Final Dataset Preview",
                "",
                "```text",
                cleaned_df.head(10).to_string(),
                "```",
                "",
                "---",
                "*Report generated automatically by Dum-E.*",
                "",
            ]
        )

        path = Path(self.report_path)
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text("\n".join(report), encoding="utf-8")

        self.log(f"✓ Report written to: {path}")

    # ================================================================
    # LLM
    # ================================================================

    def ask_llm(self, prompt: str) -> str:
        response = chat(
            model=self.model,
            messages=[
                {
                    "role": "user",
                    "content": prompt,
                }
            ],
            format="json",
            options={
                "temperature": 0,
            },
        )

        return response["message"]["content"]

    def infer_types(self, df: pd.DataFrame) -> dict:
        sample = df.head(10).to_dict(orient="records")

        pandas_dtypes = {
            col: str(dtype)
            for col, dtype in df.dtypes.items()
        }

        prompt = f"""
You are Dum-E, a data cleaning agent.

Infer the intended semantic datatype of every dataframe column.

Allowed types:
- id
- numeric
- categorical
- datetime
- text

Rules:
- IDs are NOT categorical.
- Datetime columns are NOT categorical.
- Look at column names, pandas dtype and the first 10 rows.
- Salary, age, quantity, price, score etc. are generally numeric when
  their values support that interpretation.
- Names, email addresses and free-form descriptions are text.
- Repeated finite labels such as gender, department and city are categorical.
- A column containing dates must be datetime even if pandas currently stores
  it as object/string.
- Return ONLY a JSON object mapping column names to one allowed type.

Pandas dtypes:
{json.dumps(pandas_dtypes, indent=2)}

First 10 rows:
{json.dumps(sample, default=str, indent=2)}
"""

        raw = self.ask_llm(prompt)
        schema = json.loads(raw)

        if set(schema.keys()) != set(df.columns):
            missing = set(df.columns) - set(schema.keys())
            extra = set(schema.keys()) - set(df.columns)
            raise ValueError(
                f"Invalid schema from Dum-E. Missing={missing}, Extra={extra}"
            )

        invalid_types = {
            col: dtype
            for col, dtype in schema.items()
            if dtype not in self.ALLOWED_TYPES
        }

        if invalid_types:
            raise ValueError(
                f"LLM returned unsupported semantic types: {invalid_types}"
            )

        return schema

    # ================================================================
    # CLASSIFICATION
    # ================================================================

    def classify(self, df: pd.DataFrame):
        return classify_values(df, self.schema)

    # ================================================================
    # INVALID -> MISSING
    # ================================================================

    def promote_invalid_to_missing(
        self,
        df: pd.DataFrame,
        classification_report: dict,
    ) -> pd.DataFrame:
        """
        Promote values that remain invalid for their expected semantic type
        to NaN candidates. The user then decides how those missing values
        should be handled.
        """
        df = df.copy()
        changes = []

        for column, report in classification_report.items():
            invalid_indexes = report.get("invalid", [])

            for index in invalid_indexes:
                old_value = df.at[index, column]
                df.at[index, column] = pd.NA

                changes.append(
                    {
                        "column": column,
                        "index": index,
                        "old": old_value,
                    }
                )

        if changes:
            lines = [
                f"Invalid values promoted to missing candidates: `{len(changes)}`",
                "",
            ]

            for change in changes[:50]:
                lines.append(
                    f"- `{change['column']}` row `{change['index']}`: "
                    f"`{change['old']}` → `NaN`"
                )

            if len(changes) > 50:
                lines.append(
                    f"- ... {len(changes) - 50} additional values not shown."
                )

            self.record(
                "Invalid Value Resolution",
                "\n".join(lines),
            )
        else:
            self.record(
                "Invalid Value Resolution",
                "No unresolved invalid values were found.",
            )

        return df

    # ================================================================
    # MISSING VALUES
    # ================================================================

    def handle_missing_values(
        self,
        df: pd.DataFrame,
        classification_report: dict,
    ) -> pd.DataFrame:

        columns_with_missing = [
            column
            for column, report in classification_report.items()
            if report.get("missing")
        ]

        if not columns_with_missing:
            self.log("✓ No missing values require user action.")
            self.record(
                "Missing Value Handling",
                "No missing values were present after normalization and cleaning.",
            )
            return df

        self.log("\n" + "=" * 60)
        self.log("MISSING VALUES REQUIRE USER DECISION")
        self.log("=" * 60)

        for column in columns_with_missing:
            while True:
                missing_count = int(df[column].isna().sum())
                total = len(df)
                percentage = (
                    (missing_count / total) * 100
                    if total
                    else 0
                )

                self.log(
                    f"\nColumn: {column}\n"
                    f"Missing: {missing_count}\n"
                    f"Ratio: {missing_count}/{total}\n"
                    f"Percentage: {percentage:.2f}%\n"
                    f"Available methods: "
                    f"{', '.join(sorted(AVAILABLE_METHODS))}"
                )

                method = input(
                    f"What should Dum-E do with '{column}'? "
                ).strip().lower()

                if method not in AVAILABLE_METHODS:
                    self.log(
                        f"\n❌ '{method}' is not a Dum-E capability."
                    )
                    self.log(
                        "Available tools: "
                        + ", ".join(sorted(AVAILABLE_METHODS))
                    )
                    continue

                try:
                    before_missing = int(df[column].isna().sum())

                    df = missing_value_handler(
                        df,
                        column,
                        method,
                    )

                    after_missing = int(df[column].isna().sum())

                    self.record(
                        f"Missing Value Handling - {column}",
                        f"- Missing before: `{before_missing}`\n"
                        f"- Ratio: `{before_missing}/{total}`\n"
                        f"- Percentage: `{percentage:.2f}%`\n"
                        f"- User selected: `{method}`\n"
                        f"- Missing after: `{after_missing}`",
                    )

                    self.log(f"✓ {column} → {method}")
                    break

                except (ValueError, TypeError, KeyError) as exc:
                    self.log(
                        f"\n❌ Cannot apply '{method}' to '{column}'."
                    )
                    self.log(str(exc))
                    self.log("Choose another method.")

        return df

    # ================================================================
    # CLEANING TOOLS
    # ================================================================

    def run_repair_tools(self, df: pd.DataFrame) -> pd.DataFrame:
        numeric_columns = [
            col
            for col, dtype in self.schema.items()
            if dtype == "numeric"
        ]

        datetime_columns = [
            col
            for col, dtype in self.schema.items()
            if dtype == "datetime"
        ]

        categorical_columns = [
            col
            for col, dtype in self.schema.items()
            if dtype == "categorical"
        ]

        # Word numbers
        self.log("\n[3] Converting word-based numbers...")
        before = df.copy()
        df = word_to_num(df)
        self._record_dataframe_changes(
            "Word Number Conversion",
            before,
            df,
        )

        # Numeric representations
        self.log("\n[4] Cleaning numeric representations...")
        before = df.copy()
        if numeric_columns:
            df = numeric_cleaner(df, numeric_columns)
        self._record_dataframe_changes(
            "Numeric Cleaning",
            before,
            df,
        )

        # Datetime representations
        self.log("\n[5] Cleaning datetime representations...")
        before = df.copy()
        if datetime_columns:
            df = datetime_cleaner(df, datetime_columns)
        self._record_dataframe_changes(
            "Datetime Cleaning",
            before,
            df,
        )

        # Categorical representations
        self.log("\n[6] Normalizing categorical values...")
        before = df.copy()
        if categorical_columns:
            df = categorical_cleaner(df, categorical_columns)
        self._record_dataframe_changes(
            "Categorical Cleaning",
            before,
            df,
        )

        return df

    # ================================================================
    # FINAL DTYPE ENFORCEMENT
    # ================================================================

    def final_dtype_conversion(self, df: pd.DataFrame) -> pd.DataFrame:
        self.log("\n[10] Enforcing final dtypes...")

        final_types = {}

        for column, semantic_type in self.schema.items():
            mapping = {
                "id": "id",
                "numeric": "numeric",
                "datetime": "datetime",
                "categorical": "category",
                "text": "text",
            }

            final_types[column] = mapping[semantic_type]

        before = df.copy()
        result = dtype_converter(df, final_types)

        dtype_changes = []
        for column in result.columns:
            old_dtype = str(before[column].dtype)
            new_dtype = str(result[column].dtype)

            if old_dtype != new_dtype:
                dtype_changes.append(
                    f"- `{column}`: `{old_dtype}` → `{new_dtype}`"
                )

        self.record(
            "Final Dtype Conversion",
            "\n".join(dtype_changes)
            if dtype_changes
            else "No dtype changes were required.",
        )

        return result

    # ================================================================
    # MAIN AGENT LOOP
    # ================================================================

    def clean(self, df: pd.DataFrame):
        if not isinstance(df, pd.DataFrame):
            raise TypeError("Dum-E expects a pandas DataFrame.")

        original_df = df.copy(deep=True)
        working_df = df.copy(deep=True)
        self.schema = {}
        self.events = []

        started_at = datetime.now()

        self.log("\n" + "=" * 60)
        self.log("DUM-E V0")
        self.log("=" * 60)

        try:
            # --------------------------------------------------------
            # 1. Infer schema
            # --------------------------------------------------------
            self.log("\n[1] Inferring semantic column types...")
            self.schema = self.infer_types(working_df)

            self.record(
                "Type Inference",
                "Qwen3 inferred the semantic type of each column from "
                "the column name, pandas dtype and the first 10 rows.",
            )

            self.record(
                "Inferred Schema",
                "\n".join(
                    f"- `{column}` → `{dtype}`"
                    for column, dtype in self.schema.items()
                ),
            )

            for column, dtype in self.schema.items():
                self.log(f"  {column:<25} → {dtype}")

            # --------------------------------------------------------
            # 2. Normalize known missing representations
            # --------------------------------------------------------
            self.log("\n[2] Normalizing known missing representations...")
            before = working_df.copy()
            working_df = bad_values(working_df)
            self._record_dataframe_changes(
                "Missing Representation Normalization",
                before,
                working_df,
            )

            # --------------------------------------------------------
            # 3-6. Deterministic repair tools
            # --------------------------------------------------------
            working_df = self.run_repair_tools(working_df)

            # --------------------------------------------------------
            # 7. Re-classify AFTER repair tools
            # --------------------------------------------------------
            self.log("\n[7] Re-classifying values after cleaning...")
            classification_report = self.classify(working_df)

            self.record(
                "Post-cleaning Classification",
                self._classification_summary(classification_report),
            )

            # --------------------------------------------------------
            # 8. Invalid values become missing candidates
            # --------------------------------------------------------
            self.log("\n[8] Resolving remaining invalid values...")
            working_df = self.promote_invalid_to_missing(
                working_df,
                classification_report,
            )

            # --------------------------------------------------------
            # 9. User decides missing-value treatment
            # --------------------------------------------------------
            self.log("\n[9] Checking missing values...")
            classification_report = self.classify(working_df)

            working_df = self.handle_missing_values(
                working_df,
                classification_report,
            )

            # --------------------------------------------------------
            # 10. Final dtype conversion
            # --------------------------------------------------------
            working_df = self.final_dtype_conversion(working_df)

            # --------------------------------------------------------
            # 11. Final validation
            # --------------------------------------------------------
            self.log("\n[11] Final validation...")

            remaining_missing = working_df.isna().sum()
            final_dtypes = working_df.dtypes.astype(str).to_dict()

            missing_lines = []
            for column, count in remaining_missing.items():
                missing_lines.append(
                    f"- `{column}`: `{int(count)}`"
                )

            dtype_lines = []
            for column, dtype in final_dtypes.items():
                dtype_lines.append(
                    f"- `{column}`: `{dtype}`"
                )

            self.record(
                "Final Validation",
                "### Remaining missing values\n\n"
                + "\n".join(missing_lines)
                + "\n\n### Final dtypes\n\n"
                + "\n".join(dtype_lines),
            )

            finished_at = datetime.now()

            # --------------------------------------------------------
            # Dum-E creates its own report.md
            # --------------------------------------------------------
            self.write_report(
                original_df=original_df,
                cleaned_df=working_df,
                started_at=started_at,
                finished_at=finished_at,
            )

            self.log("\n" + "=" * 60)
            self.log("DUM-E CLEANING COMPLETE")
            self.log("=" * 60)

            return working_df, self.schema

        except Exception as exc:
            # Even failed runs get an audit trail.
            finished_at = datetime.now()
            self.record(
                "Run Failed",
                f"`{type(exc).__name__}`: {exc}",
            )

            try:
                self.write_report(
                    original_df=original_df,
                    cleaned_df=working_df,
                    started_at=started_at,
                    finished_at=finished_at,
                )
            except Exception:
                # Do not hide the original exception if report generation fails.
                pass

            raise

    # ================================================================
    # CLASSIFICATION REPORT SUMMARY
    # ================================================================

    @staticmethod
    def _classification_summary(report: dict) -> str:
        lines = []

        for column, info in report.items():
            parts = []

            for key in (
                "numeric",
                "word_numeric",
                "formatted_numeric",
                "datetime",
                "missing",
                "invalid",
                "valid",
            ):
                count = len(info.get(key, []))
                if count:
                    parts.append(f"{key}={count}")

            summary = ", ".join(parts) if parts else "no classified values"
            lines.append(f"- `{column}`: {summary}")

        return "\n".join(lines)
